[0.289s] Invoking command in '/home/omron/Omron_LD/src/om_aiv_util': CMAKE_PREFIX_PATH=/home/omron/Omron_LD/install/om_aiv_msg:/home/omron/Omron_LD/install/ld_visualisation PYTHONPATH=/home/omron/Omron_LD/install/om_aiv_util/lib/python3.8/site-packages:/home/omron/Omron_LD/install/om_aiv_msg/lib/python3.8/site-packages:/home/omron/Omron_LD/install/om_aiv_util/lib/python3.8/site-packages:/home/omron/Omron_LD/install/om_aiv_navigation/lib/python3.8/site-packages:/opt/ros/foxy/lib/python3.8/site-packages /usr/bin/python3 setup.py egg_info --egg-base ../../build/om_aiv_util build --build-base /home/omron/Omron_LD/build/om_aiv_util/build install --prefix /home/omron/Omron_LD/install/om_aiv_util --record /home/omron/Omron_LD/build/om_aiv_util/install.log --single-version-externally-managed
[0.511s] Traceback (most recent call last):
[0.511s]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2859, in get_entry_map
[0.513s]     ep_map = self._ep_map
[0.513s]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2817, in __getattr__
[0.513s]     raise AttributeError(attr)
[0.513s] AttributeError: _ep_map
[0.513s] 
[0.514s] During handling of the above exception, another exception occurred:
[0.514s] 
[0.514s] Traceback (most recent call last):
[0.514s]   File "setup.py", line 7, in <module>
[0.514s]     setup(
[0.514s]   File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 143, in setup
[0.514s]     _install_setup_requires(attrs)
[0.514s]   File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 131, in _install_setup_requires
[0.515s]     dist = distutils.core.Distribution(dict(
[0.515s]   File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 445, in __init__
[0.515s]     for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
[0.515s]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 657, in <genexpr>
[0.515s]     for entry in dist.get_entry_map(group).values()
[0.515s]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2861, in get_entry_map
[0.515s]     ep_map = self._ep_map = EntryPoint.parse_map(
[0.515s]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2528, in parse_map
[0.516s]     maps = {}
[0.516s] KeyboardInterrupt
[0.532s] Invoked command in '/home/omron/Omron_LD/src/om_aiv_util' returned '-2': CMAKE_PREFIX_PATH=/home/omron/Omron_LD/install/om_aiv_msg:/home/omron/Omron_LD/install/ld_visualisation PYTHONPATH=/home/omron/Omron_LD/install/om_aiv_util/lib/python3.8/site-packages:/home/omron/Omron_LD/install/om_aiv_msg/lib/python3.8/site-packages:/home/omron/Omron_LD/install/om_aiv_util/lib/python3.8/site-packages:/home/omron/Omron_LD/install/om_aiv_navigation/lib/python3.8/site-packages:/opt/ros/foxy/lib/python3.8/site-packages /usr/bin/python3 setup.py egg_info --egg-base ../../build/om_aiv_util build --build-base /home/omron/Omron_LD/build/om_aiv_util/build install --prefix /home/omron/Omron_LD/install/om_aiv_util --record /home/omron/Omron_LD/build/om_aiv_util/install.log --single-version-externally-managed
